### POST ad proposal
POST http://localhost:8080/v1/marketplaces/ads/{{ad_id}}/proposals
x-musician-id: 983caf4c-506b-4716-8da6-9d34a8f18608
Content-Type: application/json

{
  "price": {
    "amount": 2449.99,
    "currency": "EUR"
  }
}
