### POST musician instrument
POST http://localhost:8080/v1/marketplaces/ads
x-musician-id: {{musician_id}}
Content-Type: application/json

{
  "instrument": "Gibson LesPaul",
  "price": {
    "amount": 2999.99,
    "currency": "EUR"
  }
}

> {%
  client.global.set("ad_id", response.body);
%}
